system:
  ip: 0.0.0.0
  port: 8080
  env: dev

log:
  level: debug
  format: text
  dir: logs
  prefix: clover_server
  console: true
  file: true
  rotate:
    enabled: true
    interval: daily
    maxAgeDays: 7

db:
  host: localhost
  port: 3306
  username: root
  password: rewrite123
  dbname: clover
  charset: utf8mb4
  debug: false
  source: mysql

db1:
  host: localhost
  port: 3306
  username: root
  password: rewrite123
  dbname: clover
  charset: utf8mb4
  debug: false
  source: mysql
