system:
  ip: 0.0.0.0
  port: 8080
  env: dev
  gin_mode: release
log:
  level: debug
  format: text
  dir: logs
  prefix: clover_server
  console: true
  file: true
  rotate:
    enabled: true
    interval: daily
    maxAgeDays: 7
jwt:
  expire: 240
  secret: 0721
  issuer: naka
redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 1
site:
  siteInfo:
    title: ""
    enTitle: ""
    slogan: ""
    logo: ""
    beian: ""
    mode: 1
  captcha:
    enable: true
  project:
    title: ""
    icon: ""
    webPath: ""
  seo:
    keywords: ""
    description: ""
  about:
    siteDate: "2024-09-18"
    qq: https://www.fengfengzhidao.com/uploads/file/%E6%9E%AB%E6%9E%AB/qq_20231015141644.png
    wechat: https://image.fengfengzhidao.com/rj_0731/10ca538e2acd66bc81e5f777f256372.jpg
    gitee: https://gitee.com/fengfengzhidao
    bilibili: https://space.bilibili.com/359151217
    github: https://github.com/fengfengzhidao/
  login:
    qqLogin: false
    usernamePwdLogin: true
    emailLogin: false
    captcha: false
  indexRight:
    list:
    - title: 独家推广
      enable: true
    - title: 用户反馈
      enable: false
    - title: 标签云
      enable: true
    - title: 文章推荐
      enable: true
    - title: 关于我们
      enable: true
    - title: 作者推荐
      enable: true
  article:
    noExamine: true
    commentLine: 4
email:
  domain: smtp.qq.com
  port: 587
  sendEmail: 
  authCode: ""
  sendNickname: 
  ssl: true
  tls: false
qq:
  appID: "747573454"
  appKey: ""
  redirect: http://xxxxx
qiNiu:
  enable: true
  accessKey: XEe6Q41waiVlrYAfGbhFbPvD9Lhb9dKt9T-4JcIq
  secretKey: "1QkEJelBZFWqHFOMZCHU7P5T4EZ0_1__IcuYx8x7"
  bucket: kagari
  uri: http://ti7cxe1e5.hn-bkt.clouddn.com
  region: z2
  prefix: clover
  size: 3
  expiry: 60
ai:
  enable: false
  secretKey: njdfnhj6344t45347gsdhgsdh
  nickname: 
  avatar: /xxx/xxx
  abstract: 
upload:
  size: 10
  whiteList:
  - jpg
  - jpeg
  - png
  - webp
  - gif
  uploadDir: uploads/images
db:
  host: localhost
  port: 3306
  username: root
  password: rewrite123
  dbname: clover
  charset: utf8mb4
  debug: true
  source: mysql

db1:
  host: localhost
  port: 3306
  username: root
  password: rewrite123
  dbname: clover
  charset: utf8mb4
  debug: true
  source: mysql
